//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProId { get; set; }
        public Nullable<int> ProType { get; set; }
        public Nullable<int> ProCat { get; set; }
        public Nullable<int> ProSubCat { get; set; }
        public string ProName { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string MainImg { get; set; }
        public string Details { get; set; }
        public string Informaition { get; set; }
        public Nullable<bool> InStock { get; set; }
        public string ProCode { get; set; }
        public string ProSKU { get; set; }
        public Nullable<bool> SKUActive { get; set; }
        public Nullable<decimal> RegPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescrip { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<System.DateTime> Crd { get; set; }
        public Nullable<int> CrdBy { get; set; }
        public Nullable<System.DateTime> Lmd { get; set; }
        public Nullable<int> LmdBy { get; set; }
    }
}
